name: GLS Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GLS_USER: ${{ secrets.GLS_USER }}
      GLS_PASS: ${{ secrets.GLS_PASS }}
      SUPABASE_URL_SYNC_LOGS: ${{ secrets.SUPABASE_URL_SYNC_LOGS }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scraper.js
